name: YouTubeVideoDownloader

on: workflow_dispatch
jobs: 
  download: 
        name: run
        runs-on: ubuntu-latest
        steps:
          - name: requied
            run: | 
                 mkdir -p ~/.local/bin
                 curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o ~/.local/bin/yt-dlp
                 chmod a+rx ~/.local/bin/yt-dlp
          - name: download
            run: | 
                 yt-dlp --update
                 yt-dlp --version
                 yt-dlp -P /home/yt-dlp-savepoint/ -o "savevideo.%(ext)s" --cookies /home/yt-dlp-authinfo/youtube-cookies.txt "https://www.youtube.com/watch?v=nZMCCcYayMc"
          - name: check
            run: | 
                yt-dlp --filepath
          - name: archive
            uses: actions/upload-artifact@v4
            with: 
                  name: archivefile
                  path: home/yt-dlp-savepoint/savevideo.mp4




    #><<<}}|~<$€%>$h hydroelectricities gfgggshsbsbdbshshsjsjejdjdksksksksksksksjsjssjskskksksksskksskksskksksskskskshjshsgsgsghsnwnnannajanwnwnws
