name: YouTubeVideoDownloader

on: workflow_dispatch
jobs: 
  download: 
        name: run
        runs-on: ubuntu-latest
        steps:
          - name: requied
            env: 
                 YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
            run: | 
                 #Install deno
                 curl -fsSL https://deno.land/install.sh | sh
                 echo "$HOME/.deno/bin" >> "$GITHUB_PATH"
                 
                 #Install yt-dlp
                 mkdir -p ~/.local/bin
                 curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o ~/.local/bin/yt-dlp
                 chmod a+rx ~/.local/bin/yt-dlp
                 
                 #setup youtube cookies
                 mkdir -p $GITHUB_WORKSPACE/yt-dlp-authinfo
                 printf '%s\n' "$YOUTUBE_COOKIES" > $GITHUB_WORKSPACE/yt-dlp-authinfo/youtube-cookies.txt
                 
          - name: download
            run: | 
                 deno --version
                 yt-dlp --update
                 yt-dlp --version
                 yt-dlp --verbose -f bv*[vcodec=h264]+ba[acodec=mp4a]/b -P $GITHUB_WORKSPACE/yt-dlp-savepoint/ -o "savevideo.%(ext)s" --cookies $GITHUB_WORKSPACE/yt-dlp-authinfo/youtube-cookies.txt "https://www.youtube.com/watch?v=nZMCCcYayMc"
          - name: after
            run: | 
                rm -f $GITHUB_WORKSPACE/yt-dlp-authinfo/youtube-cookies.txt
          - name: archive
            uses: actions/upload-artifact@v4
            with: 
                  name: archivefile
                  path: ${{ github.workspace }}/yt-dlp-savepoint/




    #><<<}}|~<$€%>$h hydroelectricities gfgggshsbsbdbshshsjsjejdjdksksksksksksksjsjssjskskksksksskksskksskksksskskskshjshsgsgsghsnwnnannajanwnwnwsdjdjdkdjeijdiiejeejejekjjdjdjfjrkrirjrkrkrjfjdjfheheheuueieiririrurjehdjejejejjedjdjdknffnfjdydydjdjjdjdjdjdjdjjdjdjddjjdjdjdjjdkd
