on: workflow_dispatch
jobs: 
  download: 
        name: run
        runs-on: ubuntu-latest
        steps:
          - name: requied
            run: sudo apt install yt-dlp
          - name: download
            run: yt-dlp --update
                 yt-dlp --version
        
